Used shellcheck

diff --git a/scripts/git/dogit b/scripts/git/dogit
--- a/scripts/git/dogit
+++ b/scripts/git/dogit
@@ -1,58 +1,60 @@
 #!/bin/bash
-if [ -z $1 ]; then
+if [ -z "$1" ]; then
   FOLDER=.
 elif [ -z "$2" ]; then
   FOLDER="$1"
-elif [ $2 = home ]; then
+elif [ "$2" = home ]; then
   FOLDER="$HOME/$1"
 else
   FOLDER="$1"
 fi
 if [ -d "$FOLDER/.git" ]; then
-  cd "$FOLDER"
+  cd "$FOLDER" || { echo "Unable to CD into $FOLDER !!"; exit 1; }
   /bin/echo "$FOLDER"
   /bin/echo "Here are all the Branches:"
   /usr/bin/git branch -a
   /bin/echo "(0) or (stay) Stay here"
   /bin/echo "(1) or (change) Change to another existing Branch"
   /bin/echo "(2) or (new) Create new Branch"
-  read branch
+  read -r branch
   if [[ -z "$branch" ]]; then
     exit 1
-  elif [ $branch = 1 ] || [ $branch = change ]; then
+  elif [ "$branch" = "1" ] || [ "$branch" = "change" ]; then
     /bin/echo "Enter name of branch"
-    read name
+    read -r name
     if [[ -z "$name" ]]; then
       exit 1
     fi
     /usr/bin/git checkout "$name"
-    if [ $? -ne 0 ]; then
+    gcos=$?
+    if [ "$gcos" -ne "0" ]; then
       echo "Sorry, that branch does NOT exist!"
       exit 1
-    fi  
-    
-  elif [ $branch = 2 ] || [ $branch = new ]; then
+    fi
+
+  elif [ "$branch" = "2" ] || [ "$branch" = "new" ]; then
     /bin/echo "Enter name for new branch"
-    read name
+    read -r name
     if [[ -z "$name" ]]; then
       exit 1
     fi
     /usr/bin/git checkout -b "$name"
-    if [ $? -eq 0 ]; then
+    gcobs=$?
+    if [ "$gcobs" -eq "0" ]; then
       /usr/bin/git push -u origin HEAD
-    else 
+    else
       /bin/echo "Unable to make new branch"
-      exit 1  
+      exit 1
     fi
   fi
   /bin/echo "(1) or (pull) Just Pull and Wipe my code. Run only before changes!"
   /bin/echo "(2) or (push) Will Pull and Push when your Feature Complete!"
-  read well
+  read -r well
   if [[ -z "$well" ]]; then
       exit 1
-  elif [ $well = 1 ] || [ $well = pull ]; then
+  elif [ "$well" = "1" ] || [ "$well" = "pull" ]; then
     /opt/profiles/scripts/git/gpull "$FOLDER"
-  elif [ $well = 2 ] || [ $well = push ]; then
+  elif [ "$well" = "2" ] || [ "$well" = "push" ]; then
   while :
    do
     /bin/echo "Here are your untracked/unstaged/changed...files:"
@@ -61,31 +63,31 @@ if [ -d "$FOLDER/.git" ]; then
     /bin/echo "(1) (discard) Discard changes made in file!"
     /bin/echo "(2) (add) Add file to be staged."
     /bin/echo "(3) (remove) Remove file so it's not staged."
-    read todo
+    read -r todo
     if [[ -z "$todo" ]]; then
       exit 1
-    elif [ $todo = 1 ] || [ $todo = discard ]; then
+    elif [ "$todo" = "1" ] || [ "$todo" = "discard" ]; then
       /bin/echo "enter path/file:"
-      read filename
+      read -r filename
       if [[ -z "$filename" ]]; then
         exit 1
       fi
       /usr/bin/git checkout -- "$filename"
-    elif [ $todo = 2 ] || [ $todo = add ]; then
+    elif [ "$todo" = "2" ] || [ "$todo" = "add" ]; then
       /bin/echo "enter path/file:"
-      read filename
+      read -r filename
       if [[ -z "$filename" ]]; then
         exit 1
-      fi      
+      fi
       /usr/bin/git add "$filename"
-    elif [ $todo = 3 ] || [ $todo = remove ]; then
+    elif [ "$todo" = "3" ] || [ "$todo" = "remove" ]; then
       /bin/echo "enter path/file:"
-      read fiilename
+      read -r filename
       if [[ -z "$filename" ]]; then
         exit 1
-      fi      
+      fi
       /usr/bin/git rm --cached "$filename"
-    elif [ $todo = 0 ]; then
+    elif [ "$todo" = "0" ]; then
       break
     fi
    done
diff --git a/scripts/git/gpull b/scripts/git/gpull
--- a/scripts/git/gpull
+++ b/scripts/git/gpull
@@ -3,27 +3,28 @@ clear
 if [ -z "$1" ];		then
 	/bin/echo "Please enter you GIT Folder"
 	exit 1
-else	
+else
 	/bin/echo "Warning: All local code, in $1, on this PC will be wiped out!!!"
 	/bin/echo "Please type: yes (hit enter), to do a git pull to make your local copy up to date!"
-	read agree
-	if [ $agree = yes ];	then 
-		cd "$1"
+	read -r agree
+	if [ "$agree" = "yes" ]; then
+		cd "$1" || { echo "Unable to CD into $1 !!"; exit 1; }
 		branch=$(git symbolic-ref --short -q HEAD)
 		branch=${branch:-HEAD}
-		/usr/bin/git pull origin $branch
-		if [ $? -eq 0 ];	then
+		/usr/bin/git pull origin "$branch"
+                gpobs=$?
+		if [ "$gpobs" -eq "0" ]; then
 			/bin/echo "Updated..."
-			read -n 1 -p "Press any key to continue..."
+			read -r -n 1 -p "Press any key to continue..."
 		else
 			/bin/echo "Error!!!!"
-			read -n 1 -p "Hit a key..."
+			read -r -n 1 -p "Hit a key..."
 			exit 1
 		fi
 		/bin/echo "thanks"
 	else
 		/bin/echo "Skipped update..."
-		read -n 1 -p "Press any key to continue..."
+		read -r -n 1 -p "Press any key to continue..."
 		/bin/echo ""
 	fi
 fi
diff --git a/scripts/git/gpull-and-push b/scripts/git/gpull-and-push
--- a/scripts/git/gpull-and-push
+++ b/scripts/git/gpull-and-push
@@ -3,80 +3,83 @@ clear
 if [ -z "$1" ];     then
     /bin/echo "Please enter you GIT Folder"
     exit 1
-else    
-    cd "$1"
+else
+    cd "$1" || { echo "Unable to CD into $1 !!"; exit 1; }
     /usr/bin/git status -s
     branch=$(git symbolic-ref --short -q HEAD)
     branch=${branch:-HEAD}
     /bin/echo "Did you see any files that you must first add using: git add file ?"
     /bin/echo "Please type: yes/no (then hit enter). yes will add the files, no will skip them."
-    read safe
-    if [ $safe = yes ]; then
+    read -r safe
+    if [ "$safe" = "yes" ]; then
         /usr/bin/git add --all .
-    else    
-        if [ $safe = no ];  then
+    else
+        if [ "$safe" = "no" ];  then
             echo "Ok"
         else
             exit 1
         fi
-    fi  
+    fi
     /bin/echo "Are you feature complete and working?"
     /bin/echo "Please type: yes (then hit enter), to do a git pull/push to make $1 up to date!"
-    read agree
-    if [ $agree = yes ];    then 
+    read -r agree
+    if [ "$agree" = "yes" ]; then
         /bin/echo "Please enter your commit message now: What features are added/removed?"
         while :
         do
-            read commit
-            LEN=$(echo ${#commit})
-            if [ $LEN -lt 5 ];      then
+            read -r commit
+            LEN=${#commit}
+            if [ "$LEN" -lt "5" ]; then
                 /bin/echo "Please enter your a commit message! What did you work on?"
             else
                 break
-            fi  
+            fi
         done
         /usr/bin/git commit -a -m "$commit"
-        if [ $? -eq 0 ];    then
+        gcams=$?
+        if [ "$gcams" -eq "0" ]; then
             /bin/echo "I applied your commit message, $commit"
         else
             /bin/echo "Opps"
-            read -n 1 -p "Hit a key to abort!"
+            read -r -n 1 -p "Hit a key to abort!"
             exit 1
         fi
         /usr/bin/git status
-        read -n 1 -p "Ready to pull in new code? Hit any key..."
-        /usr/bin/git pull origin $branch
-        if [ $? -eq 0 ];    then
+        read -r -n 1 -p "Ready to pull in new code? Hit any key..."
+        /usr/bin/git pull origin "$branch"
+        ubgpos=$?
+        if [ "$ubgpos" -eq "0" ]; then
             /bin/echo "done with pulling."
         else
             /bin/echo "Opps"
-            read -n 1 -p "Hit a key to abort!"
+            read -r -n 1 -p "Hit a key to abort!"
             exit 1
         fi
         /bin/echo "Ready to save your work"
-        read -n 1 -p "Press any key to continue..."
-        /usr/bin/git push origin $branch
+        read -r -n 1 -p "Press any key to continue..."
+        /usr/bin/git push origin "$branch"
+        ubgpobs=$?
         #main
-        if [ $? -eq 0 ];    then
+        if [ "$ubgpobs" -eq "0" ]; then
             /bin/echo "Super job!"
         else
             /bin/echo "Opps"
-            read -n 1 -p "Hit a key to abort!"
+            read -r -n 1 -p "Hit a key to abort!"
             exit 1
         fi
         #/bin/echo "Update MainSite.com?"
         #/bin/echo "Have you tested this yet? If working, type: yes (then hit enter)."
-        #   read worked
-        #if [ $worked = yes ];  then
+        #   read -r worked
+        #if [ "$worked" = "yes" ]; then
         #   /usr/bin/ssh -t mysite "cd /var/www/mainsite; /usr/bin/git pull origin master"
         #   /bin/echo "thanks"
         #fi
-        read -n 1 -p "Press any key to exit"
+        read -r -n 1 -p "Press any key to exit"
         /bin/echo ""
         exit 0
     else
         /bin/echo "Skipped update..."
-        read -n 1 -p "Press any key to continue..."
+        read -r -n 1 -p "Press any key to continue..."
         /bin/echo ""
         exit 1
     fi
